### ISSUE TITLE
Possible typo on partial effects

### ISSUE THREAD

**Issue by pollytatouin** [tyleransom/EconometricsLabs#4] opened 2023-01-03 18:06 UTC
Hi professor,

Looking at your econometrics cheatsheet, I am wondering if there is a typo regarding the partial effects of covariates in the Multiple Regression Model section.

Specifically, you correctly specify that the _x_ are residualized, but shouldn't this apply to the _y_ as well? I'm saying this based on the Frish-Waugh-Lovell theorem.

**Comment by tyleransom** [comment] 2023-01-03 19:22
Hi, thanks for bringing this to my attention. You are correct that the FWL theorem uses residualized y (see the second equation on the [Wikipedia page](https://en.wikipedia.org/wiki/Frisch%E2%80%93Waugh%E2%80%93Lovell_theorem)), whereas the [example in Lab 4](https://github.com/tyleransom/EconometricsLabs/blob/master/lab4.Rmd#L98) only residualizes the x.

Let's see how this differs from the example in my lab using R:

```r
# load the data
library(tidyverse)
library(modelsummary)
df <- mtcars %>% as_tibble()
```

Basic regression using `mtcars` dataset, where `cyl` is coefficient of interest:

```r
summary(lm(mpg ~ cyl + disp + hp, data = df))

Call:
lm(formula = mpg ~ cyl + disp + hp, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.0889 -2.0845 -0.7745  1.3972  6.9183 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) 34.18492    2.59078  13.195 1.54e-13 ***
cyl         -1.22742    0.79728  -1.540   0.1349    
disp        -0.01884    0.01040  -1.811   0.0809 .  
hp          -0.01468    0.01465  -1.002   0.3250    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 3.055 on 28 degrees of freedom
Multiple R-squared:  0.7679,	Adjusted R-squared:  0.743 
F-statistic: 30.88 on 3 and 28 DF,  p-value: 5.054e-09
```

Now residualize `cyl` only:

```r
est1 <- lm(cyl ~ disp + hp, data = df)
summary(lm(mpg ~ est1$residuals, data = df))

Call:
lm(formula = mpg ~ est1$residuals, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.8351  -3.5281  -0.5277   1.8950  13.7914 

Coefficients:
               Estimate Std. Error t value Pr(>|t|)    
(Intercept)      20.091      1.072  18.735   <2e-16 ***
est1$residuals   -1.227      1.583  -0.775    0.444    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 6.066 on 30 degrees of freedom
Multiple R-squared:  0.01965,	Adjusted R-squared:  -0.01303 
F-statistic: 0.6012 on 1 and 30 DF,  p-value: 0.4442
```


Now residualize both `mpg` and `cyl`:


```r
est2 <- lm(mpg ~ disp + hp, data=df)
summary(lm(est2$residuals ~ est1$residuals, data = df))

Call:
lm(formula = est2$residuals ~ est1$residuals, data = df)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.0889 -2.0845 -0.7745  1.3972  6.9183 

Coefficients:
                 Estimate Std. Error t value Pr(>|t|)
(Intercept)     1.695e-16  5.218e-01   0.000    1.000
est1$residuals -1.227e+00  7.702e-01  -1.594    0.122

Residual standard error: 2.952 on 30 degrees of freedom
Multiple R-squared:  0.07804,	Adjusted R-squared:  0.04731 
F-statistic: 2.539 on 1 and 30 DF,  p-value: 0.1215
```

In the end, they each give the same coefficient estimate, but different standard errors. I'll have to think more about why this is the case, but for now it seems that there is nothing incorrect. But please engage further if you disagree or if something else is unclear! Thanks again for bringing this up.

**Comment by pollytatouin** [comment] 2023-01-04 21:12
Explaining the same coefficient value, I get :

```math
\beta_{2FWL} = (X'_2M'_1M_1X_2)^{-1}X'_2M_1Y = (X'_2M'_1M_1X_2)^{-1}X'_2M'_1M_1Y    
```
by idempotency.

The cheatsheet (CS) model implies this regression (Y is not residualized):
```math
Y = M_1X_2\beta_2 + U 
```
$$ min (Y-M_1X_2\beta_2)'(Y-M_1X_2\beta_2) = min (Y'Y-Y'M_1X_2\beta_2 - \beta'_2X'_2M'_1Y +  \beta'_2X'_2M'_1M_1X_2\beta_2$$

$$ FOC: $$

$$ -2X'_2M'_1Y + 2X'_2M'_1M_1X_2\beta_2 = 0 $$

$$ \beta_{2CS} = (X'_2M'_1M_1X_2)^{-1}X'_2M'_1Y = (X'_2M'_1M_1X_2)^{-1}X'_2M'_1M_1Y     $$

Again, the idempotency brings back all the $M_1$'s to make the expression equivalent.

For the variance though, I haven't succeeded at explaining it mathematically yet. But from the regression outputs we see that the FWL way gives a SE much closer to the true value than when using CS. I suspect the difference in SE between the true value and FWL comes from incorrect degrees of freedom (the model doesn't know other parameters were used in a first step).

**Comment by tyleransom** [comment] 2023-01-05 17:39
Nice work! I agree with you that the SE difference is likely due to some degrees of freedom discrepancy.

If it's all right with you, I'll close this issue. I believe that the way I present it in the lab is consistent with how it's written in Wooldridge's book. While this implementation is not perfectly correct with respect to the FWL theorem, I believe it's more accessible to introductory students.

Feel free to re-open the issue if you have more questions or proposed corrections. Thanks!

**Closed as completed by tyleransom** 2023-01-05 17:39 UTC
